INSERT INTO ROLE (ROLE_ID, NAME) SELECT 1, 'USER' FROM DUAL
WHERE NOT EXISTS (Select 1 from ROLE where name = 'USER');

INSERT INTO ROLE (ROLE_ID, NAME) SELECT 2, 'ADMIN' FROM DUAL
WHERE NOT EXISTS (Select 2 from ROLE where name = 'ADMIN');